//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Enrollment = new HashSet<Enrollment>();
        }
    
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string Credits { get; set; }
    
        public virtual ICollection<Enrollment> Enrollment { get; set; }
    }
}
